README.md
The README previously opened up with a description of some implementation details, but zero high-level information on what it actually achieves with that. In this PR I:
- Move down the legal topics to the bottom
- GitHub prominently displays the license in the side bar already
- Remove the "TODO" section
- Everyone knows where to find the `Issues` tab
- Rewrite the "Introduction" section using the bullet-points from [our donation proposal](https://github.com/open-telemetry/community/issues/1918#issue-2107828565)
=> doc: restructure and extend README

interpreter/php/decode_amd64.c, interpreter/php/decode_amd64.h, interpreter/python/decode_amd64.c, interpreter/python/decode_amd64.h, libpf/pfelf/testdata/fixed-address.c, libpf/pfelf/testdata/test.c, reporter/testdata/test.c, tpbase/fsbase_decode_amd64.c, tpbase/fsbase_decode_amd64.h, tpbase/libc_decode_amd64.c, tpbase/libc_decode_amd64.h, utils/coredump/testsources/c/brokenstack.c, utils/coredump/testsources/c/sig.c, utils/coredump/testsources/c/stackalign.c
To clarify for readers: The eBPF C code in this repository is GPL licensed (and not affected by this PR). We have additional non-eBPF code however, and that is licensed under Apache2.
=> license: Add preamble to non-eBPF C/include files

README.md
Fixes a linkage problem and should hopefully make the aarch64 macOS executable work on any machine now. I tested this with a second aarch64 Mac and it seems to be fine now.
Closes #4
=> doc: update devfiler download

.dockerignore, .gitignore, Dockerfile, Makefile
Running the build container as root (default) creates temporary files owning root outside the container. A `make clean` will run into permission denied.
=> Run build container as user

docs/symb-proto/README.md, docs/symb-proto/symbfile.proto
This adds documentation on our symbol protocol. Largely just pasted over from our internal repository, with some rephrasing and restructuring.
=> doc: add symbol upload protocol specification

Dockerfile
golangci-lint install.sh uses jq to parse downloaded files. Install it to avoid errors on missing jq when building the Docker image (that still builds fine).
=> Dockerfile: install jq

Makefile, main.go, vc/vc.go
This PR adds code to plumb agent version, revision and build times through the Makefile and initializes the previously default-initialized `Config` fields with proper values. It effectively mirrors what we are also doing in the Elastic distribution of the agent.
=> Add build and version info

reporter/otlp_reporter.go
We'd previously needlessly send a bunch of empty attributes:
This PR adds a check to omit those.
=> Don't send empty sample attributes

containermetadata/containermetadata.go
Make the log message more precise.
=> Clearer log message in getContainerMetadataCache()

libpf/trace.go, processmanager/manager.go, processmanager/processinfo.go, processmanager/types.go, reporter/otlp_reporter.go, tracer/tracer.go
This reworks `ProcessManager` and the OTLP reporter to send out memory mappings in **ELF address space** as explained [here](https://github.com/open-telemetry/opentelemetry-proto/pull/553#issuecomment-2163412417).
CC @brancz
=> Properly populate reported mappings with ELF VAs

interpreter/dotnet/instance.go, processmanager/manager_test.go, processmanager/processinfo.go, reporter/iface.go, reporter/otlp_reporter.go, tools/coredump/coredump.go, tracer/ebpf_integration_test.go, tracer/tracer.go
There was [some interest](https://cloud-native.slack.com/archives/C03J794L0BV/p1718379810177579) in extending the reporter interface to allow agent-as-a-libray consumers of this repository to experiment with automatic symbol upload. This PR extends `ExecutableMetadata` with two new arguments:
- The interpreter kind that the executable is being reported for. As of writing, this can be `Native`, `Kernel`, or `Dotnet`
- A callback that can be used to open the executable on disk
As far as I can tell, this should provide everything to launch an executable upload / symbol extraction in the background.
=> Extend reporter interface to support symbol upload

config/config.go, config/config_test.go, env/env.go, env/env_test.go, hostmetadata/collector.go, main.go
Due to historical reasons, the code currently has a number of global variables, hidden behind types like `config.Config`.
This PR is a first step to avoid global variables by introducing the `env` package.
=> New package env to reduce global vars

hostmetadata/collector.go, main.go, platform/platform.go, platform/platform_test.go
`env` often refers to environment variables, but here we refer code for compute platforms.
=> Rename env/ to platform/

tools/coredump/main.go, tools/coredump/modulestore/store.go
modulecache is a hardcoded name for a directory used in the scope of coredump. If it does not exist, coredump will run into multiple errors. As modulecache is an essential part and also referenced in .gitignore, create it if it does not yet exist.
=> coredump: create directory modulecache

main.go
Fixing the kernel version check for amd64 from >= 4.15 to >= 4.19
=> Fix kernel version check to >= 4.19

interpreter/hotspot/instance_test.go
The `TestJavaSymbolExtraction` test would previously fail when running under qemu-user: if the application is running under emulation, the pointer addresses don't actually correspond to real memory addresses, so if the applications peeks through the curtains of emulation via `process_vm_read`, it would read back the wrong values. This PR replaces the real memory read with a mocked one from an array.
(Revived version of https://github.com/elastic/otel-profiling-agent/pull/73 that got auto-closed due to #76)
=> Hotspot tests: mock process memory reading

reporter/otlp_reporter.go
I noticed that our `ReportTraceEvent` implementation currently aggregates traces exclusively based on their trace hash. This is problematic because the trace hash no longer includes the pod-, thread-, and service names: traces with different values for the aforementioned fields would be aggregated together, incorrectly reporting the values of the first trace that was inserted for them for all following ones.
To fix this, I created a new key struct that encompasses all the fields that need to be considered when aggregating traces and moved the fields over from `traceFramesCounts`. This is equivalent to what we are doing in [the Elastic proto reporter](https://github.com/elastic/prodfiler/blob/22b64fcc7f2b14905de5c4baf7e9c563509ac529/pf-host-agent/reporter/reporter.go#L366).
=> Fix sample aggregation in reporter

interpreter/nodev8/v8.go
The prefix list generation was not updated at all when an existing mapping is seen again. To avoid extra work, create a per-mapping uint32 which is shared via pointer to the mapping and all prefixes generated from it. This allows updating the generation for all of them with one assignment.
Reported-by: Nayef Ghattas <nayef.ghattas@datadoghq.com>
=> v8: fix mappings synchronization

libpf/convenience.go, pacmask/pacmask_arm64.go, processmanager/manager_test.go, testsupport/io.go, tracer/tracer.go
math/rand/v2 has several advatages over math/rand.
See https://go.dev/blog/randv2
This change also reduces suppressions of gosec.
=> Switch to math/rand/v2

.github/workflows/env/action.yml, .github/workflows/unit-test-on-pull-request.yml, Makefile, support/run-tests.sh
Building on top of https://github.com/elastic/otel-profiling-agent/pull/80 and combining this with qemu-binfmt we can now run ARM64 tests in CI despite the continuing lack of ARM64 runners on GitHub (Microsoft, please fix!).
=> Run ARM64 tests in CI

reporter/otlp_reporter.go, reporter/otlp_reporter_test.go
* Adds a helper map to track attributes that were already inserted into `Profile.attributeTable` and avoid duplication.
- closes https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/99
=> Fix duplicate entries in Profile.AttributeTable

process/process.go
Currently, the function incorrectly always returns `0` as the modified timestamp.
The consequence is that if a new mapping has the same device ID and inode ID as a previous mapping, the [elfInfoCache](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/d7d24bc1c5eaec44f00c064dc7dc655084754156/processmanager/types.go#L87) will wrongly return the old mapping's file ID even though modified timestamps are different on those mappings ([here](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/main/processmanager/processinfo.go#L250-L255)).
We encountered this on short-lived Java workloads using JNI and sharing the same local disk (same device ID), where two different librairies had the same inode ID in consecutive runs.
=> process: fix mapping last modified timestamp

nativeunwind/elfunwindinfo/elfehframe.go
These aren't mentioned by the DWARF standard,
but they appear occasionally. `objdump` just skips them; this PR has us do the same.
=> Handle zero-length FDEs and CIEs

reporter/iface.go, reporter/otlp_reporter.go, tracehandler/tracehandler.go, tracehandler/tracehandler_test.go
As previously announced [here](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/115#pullrequestreview-2237893710), this bundles all the trace meta fields in a struct instead of passing them individually. This approach ensures that we aren't breaking the reporter interface every time we add new meta data.
CC @umanwizard
=> reporter: bundle trace meta args in a struct

.github/workflows/env/action.yml, .github/workflows/unit-test-on-pull-request.yml, .golangci.yml, Makefile, interpreter/php/decode_arm64.go, maccess/maccess_arm64.go, main.go, pacmask/pacmask_arm64.go, periodiccaller/periodiccaller_test.go
- We previously forgot to actually pass `TARGET_ARCH=xxx` to `make lint` in CI, so the ARM64 lint target didn't work as intended. 
- This PR fixes this and also addresses various lints that have previously slipped due to that misconfiguration.
- Update and pin Go version used in CI to v1.23 
- Update `golanglint-ci` to v1.60.1 (previous version is broken with new Go)
- Cherry-picked commit from https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/118 to fix periodiccaller's goroutine leak check
=> Update Go + linter and fix various linter warnings

cli_flags.go, reporter/otlp_reporter.go
Reporting a project ID originates from a SaaS setup. Currently neither users of the agent nor users of the reporter package can set the project ID and so a default value is sent every time.
In the OTel environment some element in OTel ResourceProfile should be preferred to set such a value.
=> reporter: drop project ID

cli_flags.go, host/host.go, main.go, processmanager/manager.go, processmanager/processinfo.go, processmanager/types.go, times/ktime.go, times/times.go, tools/coredump/ebpfhelpers.go, tracehandler/tracehandler.go, tracehandler/tracehandler_test.go, tracer/tracer.go
- Moved `KTime` / `GetKTime` from `util` to `times` package
- Periodic sync with realtime clock (instead of boottime monotonic)
- Added realtime clock sync interval configuration option
=> KTime: Sync with realtime clock

.github/workflows/unit-test-on-pull-request.yml, .golangci.yml, Makefile
Use the official [`golangci-lint-action`](https://github.com/golangci/golangci-lint-action) action for linting. This comes with two major benefits:
- It creates nice inline annotations on your diff if problems are found
- It takes care of caching the right paths automatically
Resolves https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/124
=> Use `golangci-lint-action` in CI

interpreter/dotnet/instance.go, processmanager/manager_test.go, processmanager/processinfo.go, reporter/iface.go, reporter/otlp_reporter.go, tools/coredump/coredump.go, tracer/ebpf_integration_test.go, tracer/tracer.go
It looks like that the context parameter of `reporter.ExecutableMetadata()` is a historical remnant.
=> Remove context from reporter.ExecutableMetadata

metrics/metrics.go, metrics/metrics_test.go, metrics/types.go
Fixes #149
This will enable profilers using the ebpf profiler as a library to export some of the internal metrics of the profiler. For example, this should allow getting more data on unwinding errors for interpreted languages.
For the interface, I added a `GetDefinitions()` method in the metrics package, which would require exposing the `metrics` package in https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/132, happy to move this elsewhere though if we think this is not the best place / API for this.
=> metrics: add an interface to get the metrics definitions

CONTRIBUTING.md
Hi all! Today is my last working day at Elastic. I've been thinking back and forth about whether I'd like to retain the maintainer position as an external contributor in my free time, but eventually decided that I realistically won't have the time to do justice to the role. I would however like to continue contributing to the project in a less critical position.
I'm thus suggesting to simply swap roles with @christos68k, currently an approver, who is effectively taking over my position as an IC responsible for the profiling agent at Elastic.
I appear to have the GitHub permissions to add a new maintainer, as well as the permissions to remove myself. Once all of the other maintainers[^1] have approved this PR, I'd be happy to apply the changes as my last action as a maintainer.
[^1]: Minus …
=> Remove Joel from maintainer list, move Christos to maintainer list

AUTHORS.md, README.md, cli_flags.go, reporter/otlp_reporter.go, tools/coredump/README.md
Before the repository got moved to Open Telemetry it was hosted as elastic/otel-profiling-agent.
=> cleanup: update references to elastic/otel-profiling-agent

processmanager/processinfo.go, reporter/iface.go, reporter/otlp_reporter.go, reporter/otlp_reporter_test.go
https://github.com/open-telemetry/semantic-conventions/pull/1329 got merged, which introduces a semantic convention for build_ids. Use this semantic convention in favor of BuildIdKind, that will be dropped with https://github.com/open-telemetry/opentelemetry-proto/pull/584.
=> reporter: use semantic convention to report build_id

interpreter/dotnet/instance.go, libpf/pfelf/file.go, processmanager/manager_test.go, processmanager/processinfo.go, reporter/iface.go, reporter/otlp_reporter.go, tools/coredump/coredump.go, tracer/ebpf_integration_test.go, tracer/tracer.go
This will allow library consumers to do something with the debuginfo discovered via .gnu_debuglink, if they wish to do so.
=> Report debuglink path to ExecutableMetadata

README.md
Fixes:  #152
The  **OTel eBPF** profiler only runs on Linux, [Building](https://github.com/open-telemetry/opentelemetry-ebpf-profiler?tab=readme-ov-file#building) has been updated to provide appropriate steps and instructions.
=> fixes: #152 Add missing information to README.md

interpreter/dotnet/data.go, interpreter/dotnet/instance.go, interpreter/hotspot/instance.go, interpreter/hotspot/method.go, interpreter/hotspot/unsigned5.go, interpreter/nodev8/v8.go, interpreter/perl/instance.go, interpreter/php/instance.go, interpreter/python/python.go, interpreter/ruby/ruby.go, libpf/trace.go, processmanager/manager_test.go, reporter/iface.go, reporter/otlp_reporter.go, tools/coredump/coredump.go, tracer/ebpf_integration_test.go
Due to legacy reasons, each interpreter kept their own state of which dynamic metadata should be sent to the reporter. Several of these caches would never expire, causing caching issues in the otlp reporter module.
This removes the caching state from all interpreters and pushes it to the reporter module. A new reporter API call FrameNeeded is added to query if a specific Frame is in the cache or not. Not all interpreter modules use the call as all the information might be available with little overhead. FrameMetadata is also updated to use the FrameID type for symmetry.
Improved are:
- reduced memory overhead as per-interpreter caches are removed
- reporter module can now control which frames need resolving
- fixes otlp to get the frames re-symbolized if its internal lru already forgot …
=> interpreters, reporter: refactor towards statelessness

.gitignore
Binary name has changed to ebpf-profiler after #164.
=> git: ignore compiled executable

Dockerfile
Debian does provide a different Go version than set in go.mod. Install Go from upstream instead of Debian packages.
=> docker: use Go version as defined in the package

reporter/iface.go, reporter/otlp_reporter.go, support/debugtracer_amd64.go, support/debugtracer_arm64.go, support/debugtracer_dummy.go, tracer/tracer.go
Based on #171, refactor reporting of kernel symbols in order to use reporter.FrameKnown() and reporter.FrameMetadata(). This allows dropping ReportFallbackSymbol from the SymbolReporter interface. As a consequence, drop special handling of kernel frames in getProfile().
ref #121
=> kernel frames, reporter: refactor towards statelessness

libpf/symbol.go, proc/proc.go, proc/proc_test.go
Reducing the kernel symbols' memory footprint by
- skipping non-text symbols when reading from `/proc/kallsyms`
- adjusting overcommitted symbols array
Additionally, we pre-allocate a relatively large symbols array to begin with parsing to avoid re-allocations.
The added test is for reproducibility / review purposes and is meant to be removed before merging.
**The test needs to be run as root / with sudo, otherwise all addresses are 0 and the test fails (as in the CI).**
Not yet measured: the effect on loading symbols from executables (pre-allocation of symbol maps may also reduce CPU overhead).
Tested on Debian 6.10.11-amd64 x86_64 with ~284k entries in `proc/kallsyms` (180k+ text symbols).
```
Memory usage before calling GetKallsyms:
Alloc = 0 MiB   TotalAlloc = 0 MiB      Sys = 8 MiB …
```
=> Reduce memory footprint of kernel symbols 

process/coredump.go, process/process.go, process/types.go, tools/coredump/new.go
The fixes the 'new' command to fallback to the coredump methods so that the coredump backed memory can be used even if the file on disk is not found. This is especially important for the vDSO, but also in case we want to import a standalone core.
Additional add an informative message once for each module which cannot be found.
=> coredump/new: allow importing cores without backing file found

interpreter/dotnet/instance.go, interpreter/dotnet/pe.go, processmanager/manager_test.go, processmanager/processinfo.go, reporter/iface.go, reporter/otlp_reporter.go, tools/coredump/coredump.go, tracer/ebpf_integration_test.go
Expose the cached status for executable metadata to callers of `SymbolReporter.ExecutableMetadata()`.
Improvements
- the reporter module can now control which executable metadata needs to be fetched
- fixes OTLP to re-fetch executable metadata if its internal lru already evicted earlier metadata
reference: #121
=> executables, reporter: refactor towards statelessness

tracer/ebpf_integration_test.go, tracer/tracer.go, tracer/types/parse.go
initializeMapsAndPrograms() provides core functionality in sizing and loading eBPF maps and programs. So far per-kernel tests only load specific named eBPF programs and therefore could not catch Linux kernel version specific issues with eBPF programs that were not loaded.
=> integration tests: add test that loads all maps and programs

design-docs/00001-off-cpu-profiling/README.md
This proposal builds on and follows the approach described in https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/114.
=> [RFC] design doc: proposal for off-cpu profiling

metrics/ids.go, metrics/metrics.json, reporter/metrics.go
Remove/obsolete left-overs of the Elastic reporter implementation.
=> Metrics: Drop unused reporter metrics

reporter/otlp_reporter.go, reporter/otlp_reporter_test.go
**What:**
This PR aims to add process Id as an attribute for each sample. This would be an addition to other attributes such as containerId, threadName etc. being sent currently.
**Why:**
Tools/services consuming the profiles sent by opentelemetry-ebpf-profiler could utilize the PID as an identifier for a process in their software/implementations.
=> Add PID as an attribute in each sample

README.md, reporter/otlp_reporter.go
With https://github.com/open-telemetry/semantic-conventions/pull/1520 `process.executable.build_id.profiling` got deprecated and renamed to `process.executable.build_id.htlhash`.
=> reporter: use htlhash attribute for profiling specific hash

reporter/otlp_reporter.go, reporter/otlp_reporter_test.go
PR #212 changed the behaviour of addProfileAttributes(). Before adding an attribute the length of the string was checked - see https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/0c58efd41280bce80cca9804896c76874d383b35/reporter/otlp_reporter.go#L747-L749
This returns to the original behaivour, where string attributes with no values are not added.
=> reporter: do not add empty attributes

host/host.go, reporter/iface.go, tracehandler/tracehandler.go, tracer/events.go, tracer/tracer.go
Requested by customers: https://github.com/parca-dev/parca-agent/issues/2778
The idea is cpuid combined w/ timestamps can enable go trace style CPU core utilization graphs and give some limited insight into scheduler workings.
=> Add CPU id to trace and trace metadata

go.mod, go.sum, main.go, reporter/otlp_reporter.go
Ensure that actively used executable info is not expired from the cache, by extending its lifetime using `GetAndRefresh()`
Fixes https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/244
=> reporter: don't expire actively used executables

proc/proc.go
We've seen multiple instances of this file being malformed and usually
we just want to skip lines that don't parse correctly.
=> Turn kernel module file parsing errors into warnings

libpf/readatbuf/readatbuf.go, libpf/readatbuf/readatbuf_test.go
Slightly simpler alternative to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/258. Also added a test case that catches the previous crash.
=> readatbuf: add missing check when reading from tail chunk

reporter/otlp_reporter.go
Similar to the reported issue https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/248 around lifetime of executables, the same issue happens for frames. So keep cached frame information alive.
=> reporter: extend lifetime for cached elements

interpreter/loaderinfo.go, libpf/pfelf/file.go, libpf/pfelf/pfelf.go, libpf/symbol.go, proc/proc.go, proc/proc_test.go, processmanager/synthdeltas.go
Turns out we figured out why users were running into "malformed" kernel module files. Turns out they were not malformed we were just parsing dashes incorrectly (with `fmt.Sscanf`).
(https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/255 was the previous attempt)
@florianl @fabled @rockdaboot
=> proc: Fix parsing Kernel Module lines where refcount is "-"

reporter/otlp_reporter.go
Noticed this while I was working on #253, change was recently introduced in d6fd2ec (original commit is [here](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/237/commits/cd17b591df7f13f2abbb4c78c0b2c5027328c792)).
=> Send thread name as ThreadNameKey not ProcessCommandKey

host/host.go, processmanager/processinfo.go, processmanager/types.go, reporter/iface.go, reporter/otlp_reporter.go, tracehandler/tracehandler.go, tracer/tracer.go
1. Added executable path collection to `processmanager`
2. Tracer will now enrich host traces with executable path
3. Reporter will report executable path with every stack trace
**TODO:**
- ~Retrieve name from `/proc/PID/status` instead of `/proc/PID/exe` to be semconv compliant (`/proc/PID/status` will have the filename truncated to `TASK_COMM_LEN-1` characters)~
Decided not to retrieve/send [process.executable.name](https://opentelemetry.io/docs/specs/semconv/attributes-registry/process/#process-executable-name) in the way that semantic conventions dictate (`Name` in `/proc/PID/status`) as this is not the executable name but the process name (see [proc_pid_status(5)](https://man7.org/linux/man-pages/man5/proc_pid_status.5.html)), which can be changed by the application (e.g. through …
=> Send executable path with every stack trace

tools/coredump/README.md, tools/coredump/new.go
Avoid full process coredumps when the ELF files are bundled. This significantly reduces the size of coredumps from large processes.
Add "coredump new -sysroot" option to specify sysroot prefix for finding the files to be bundled.
Update instructions accordingly.
=> coredump: no need for full dump with bundled files

processmanager/manager.go
If APM service name is overwritten, let the user know about this conflict with a logged warning.
=> apmint: warn user about changes in the APM service

README.md
Added a breaking change and update the OTel profiling protocol to v0.4.0. Update devfiler to a version that supports it.
=> README: provide new version of devfiler

proc/proc.go, proc/proc_test.go
parseKernelModuleLine currently fails to parse lines for nvidia kernel modules.
=> proc: handle nvidia kernel modules

internal/controller/config.go, internal/controller/controller.go, main.go
When running the agent as a collector receiver, the `CollAgentAddr` config isn't used, since we don't start any HTTP/gRPC server.
We therefore should make this config optional.
This isn't tested because the controller currently requires root to run, and therefore can't be started in the context of tests.
=> Make the CollAgentAddr config optional in controller

Makefile
Always use `NATIVE_ARCH` as `GOARCH` for `go:generate`. The previous approach will fail on systems that can't execute cross-compiled binaries on the build host (e.g. if an appropriate `qemu` binary is not installed).
Fixes #282.
=> Fix cross-compilation (#282)

.github/workflows/push-docker-image.yml, Dockerfile, Makefile
With https://github.com/open-telemetry/community/issues/2283 a Docker repo was requested and provided to host docker images for this project.
This PR helps bringing back reproducible builds. As this project does not yet produce releases the tags `latest`, that will be overwritten every time, and a timestamp are used instead.
=> docker: build and push docker builder image

interpreter/apmint/apmint.go
At the moment `Attach()` returns no error and just logs the problem, if `openAPMAgentSocket()` returns an error.
=> apmint: return error if Attach() fails

host/host.go, processmanager/processinfo.go, processmanager/types.go, reporter/base_reporter.go, reporter/internal/pdata/generate.go, reporter/internal/samples/samples.go, tracehandler/tracehandler.go, tracer/tracer.go
This PR adds support for sending process name as `process.executable.name`, abiding by current OTel [semantics](https://opentelemetry.io/docs/specs/semconv/attributes-registry/process/#process-executable-name) for that key. Instead of `Name` in `/prod/PID/status` as semconv dictates, I'm using [/proc/PID/comm](https://man7.org/linux/man-pages/man5/proc_pid_comm.5.html) which contains the same value and is simpler to parse.
Regarding these semantics, I also started a discussion in semconv WG to improve clarity as `process.executable.name` is misleading/confusing/wrong depending on interpretation so we may end up changing the key in the future.
=> Send process name as process.executable.name (/proc/PID/comm)

README.md
Starting with https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/297 the docker image to build the eBPF profiler is available for everyone.
Fixes https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/303.
=> README: drop make target docker-image as pre requirement

.github/workflows/env/action.yml, reporter/internal/pdata/generate_test.go
Drop installation of dependencies, that are not used and use `go.mod` as single source of truth for the installed Go version.
=> CI: reduce boiler plate of environment

.golangci.yml, Makefile, libpf/basehash/hash128.go, libpf/frameid.go, processmanager/manager_test.go, reporter/internal/pdata/generate.go, reporter/internal/pdata/pdata.go, tools/zstpak/lib/zstpak_test.go
Update golangci-lint to 1.63.4.
**Noteworthy changes**
- Fixing `.golangci-lint` for
```
WARN [lintersdb] The linter "gomnd" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle 
WARN [lintersdb] The linter "execinquery" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle 
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar. 
```
- Suppressing `gosec` integer overflow warnings (G115 rule), following https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/369 …
=> Bump golangci-lint to 1.63.4

reporter/collector_reporter.go, reporter/otlp_reporter.go
If the OTel collector reports profiles it clears all map entries. So to be able to report new events, the base structure needs to exist.
Thanks @rockdaboot for reporting.
=> reporter/collector: fix reporting issue

processmanager/manager.go, tracehandler/tracehandler.go, tracer/events.go, tracer/tracer.go
Updated `SymbolizationComplete` mechanism to reflect current semantics around trace processing and timestamping (no batching, in-kernel high resolution timestamps):
- Don't call `SymbolizationComplete` per-Trace, instead call it after each iteration of the perf event batch-drain loop. This introduces a call frequency upper bound (currently: 4Hz).
- Keep track of minimum `KTime` seen during trace event retrieval and report the minimum `KTime` belonging to the previous processing iteration with `SymbolizationComplete`.
- `startPollingPerfEventMonitor` is now specialized to trace event processing, this also simplifies caller logic.
**TODO:**
1. ~Generify `SymbolizationComplete`, fix #278~ Will open new PR for this.
**Also see:**
- #301
=> Rework SymbolizationComplete

processmanager/manager.go, processmanager/manager_test.go, processmanager/processinfo.go, tracehandler/tracehandler.go, tracehandler/tracehandler_test.go, tracer/events.go
- Renamed `SymbolizationComplete` to `ProcessedUntil` and moved to `processinfo.go`
- Dropped no longer needed "symbolize now" remnants
- Implemented delayed `ProcessManager.pidToProcessInfo` cleanup
Leverages #307 to ensure that process metadata is not discarded before all relevant trace events have been processed. 
Fixes #278.
You may find reviewing commit-by-commit to be simpler.
=> Delayed processing for ProcessManager.pidToProcessInfo

processmanager/manager_test.go, processmanager/processinfo.go
This change can be reviewed commit by commit.
`processmanager: make ProcessPIDExit private`
The recommended way to report new mappings or exited process SynchronizeProcess() should be used.
`processmanager: return early in processPIDExit()`
Return early from processPIDExit() if pm.pidToProcessInfo is not aware of a paritcular PID. This early return is possible, as processPIDExit() holds the global ProcessManager lock and entries in pm.pidToProcessInfo, pm.interpreters and pm.exitEvents are cleared in ProcessedUntil() while holding the lock.
=> processmanager: simplify API and return early

.github/workflows/unit-test-on-pull-request.yml
The Rust components are not yet integrated into deliverables. To not break Rust things unintentionally run basic tests in CI.
=> CI: add test for Rust components

processmanager/processinfo.go
I left debug logging as-is as the performance impact should be minimal for the normal case and moving them outside the lock could make debugging harder.
=> processmanager: Don't log inside critical areas

Cargo.lock, Cargo.toml, rust-crates/symblib/Cargo.toml
Avoid unused dependency warnings by removing those from the dependency list.
=> rust: drop anyhow dependency

support/support_amd64.go, support/support_arm64.go, support/support_others.go
This is a follow-up to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/332
In any architecture other than ARM64 and AMD64, we need this dummy tracerData so the architecture can use `libpf` as a library.
Support for these architectures is required by OpenTelemetry Collector Contrib.
See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/13069379268/job/36467659832?pr=37567
=> Use dummy support for any non-arm64 and non-amd64 archs

Cargo.toml
Cargo tools use the license field to identify and recognize the correct license of the workspace.
=> cargo: set license field

processmanager/processinfo.go
This fixes an issue introduced with dd4c52bd.
=> processmanager: Fix process exit regression (#337)

.github/workflows/unit-test-on-pull-request.yml
When running the integration tests cross-compliation tooling is not needed. As a side effect, tests pass faster without installing the unneeded overhead.
=> CI: skip environment setup

rust-crates/symblib/src/symbconv/dwarf/mod.rs, rust-crates/symblib/src/symbconv/go.rs
Use macro debug instead of eprintln for debug messages.
Follow up to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/267#discussion_r1909802362.
=> rust: use macro for debug output

README.md, processmanager/manager_test.go, processmanager/processinfo.go, support/ebpf/bpfdefs.h, support/ebpf/tracemgmt.h
coredump used to be under a different path. Fix the path to avoid confusion.
=> doc: fix path of tooling

interpreter/nodev8/v8.go
This PR brings us up to date with the latest origin/main of Node.
=> Various fixes to node/V8

reporter/config.go, reporter/otlp_reporter.go
Add support for custom gRPC dial options
This change allows users to provide additional gRPC dial options when establishing a connection to the collector. The options are appended after the default options that the reporter already sets.
This is useful for cases where users need to customize the gRPC connection behavior, such as:
- Adding custom interceptors
- Configuring custom transport credentials
- Setting custom keepalive parameters
- Adding custom headers
The change adds a new `GRPCDialOptions` field to the `Config` struct and applies these options when establishing the connection.
=> reporter: add custom gRPC dial options

Cargo.toml
Remove unused workspace dependencies (serde, ureq) from Cargo.toml that aren't referenced by any crates in the workspace.
=> cargo: remove unused workspace dependency declarations

.cargo/config.toml, .github/workflows/env/action.yml, .github/workflows/push-docker-image.yml, .github/workflows/unit-test-on-pull-request.yml, Dockerfile, Makefile
Preparative steps to add Rust to the CI and general workflows.
=> rust: preparations to integrate Rust

Dockerfile
Using `make agent` fails currently with the following error:
rustup target add x86_64-unknown-linux-musl
bash: line 1: rustup: command not found
Fix this issue by setting up directories, permission and environment variables correctly.
=> Docker: fix rust set up

Dockerfile, Makefile
Local caching tricked me when working on https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/371 so I missed a part. This should be fixed now.
How to test:
```
$ make clean
$ make docker-image
$ make agent
```
Fixes https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/373
=> Docker fixup

.github/workflows/unit-test-on-pull-request.yml
Updates the archives database as the Ubuntu image and public repositories might be out-of-sync.
Failures like `404  Not Found [IP: 52.252.75.106 80]` when installing packages for the integration tests can be mostly avoided. Same goes for missing packages.
=> Stabilize CI / integration tests

reporter/internal/pdata/generate.go
`process.executable.name` is now the base executable name, instead of process name.
**TODO**:
~1. Use newly introduced key (`process.name`) for process name~ No consensus in semconv for that key, yet.
We can review/merge this PR now and introduce `process.name` if/when it gets merged in semconv.
**Also see**:
- https://github.com/open-telemetry/semantic-conventions/issues/1736
- https://github.com/open-telemetry/semantic-conventions/issues/1928
=> Switch semantics for process.executable.name

Makefile
Proper clean up helps to not getting lost with cached elements and getting lost in debugging ...
=> Makefile: add cargo clean to target clean

internal/controller/config.go, main.go
Remove `HostName` `IPAddress` fields. They seem to be used only in the reporter
=> chore: remove unused controller.Config fields

rust-crates/symblib-capi/c/symblib.h, rust-crates/symblib-capi/src/gosym.rs, rust-crates/symblib-capi/src/lib.rs, rust-crates/symblib-capi/src/pointresolver.rs, rust-crates/symblib-capi/src/status.rs, rust-crates/symblib/src/gosym/mod.rs, rust-crates/symblib/src/symbconv/mod.rs
Implement a trait with the API for Go executables that got introduced with https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/346 and expose this trait as C API.
<details>
<summary> Go programm that uses this Rust API via the C FFI </summary>
```
executablePath := C.CString("/.../...")
defer C.free(unsafe.Pointer(executablePath))
addr := uint64(0xc0ffee)
var goRuntime *C.SymblibPointResolver
status := C.symblib_goruntime_new(executablePath, &goRuntime)
if status != C.SYMBLIB_OK {
fmt.Fprintf(os.Stderr, "Failed to create SymblibGoRuntime: %d\n", status)
return
}
defer C.symblib_goruntime_free(goRuntime)
var symbols *C.SymblibSlice_SymblibResolvedSymbol
defer C.symblib_slice_symblibresolved_symbol_free(symbols)
status = C.symblib_point_resolver_symbols_for_pc(goRuntime, …
```
=> symblib: expose API for single point lookups

.github/workflows/fossa.yml
This also requires an API key that is only available on the upstream repo and doesn't work on forks.
I missed this one during https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/395 -- sorry for the noise!
=> ci: also disable FOSSA on forks

processmanager/ebpf/ebpf.go
https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/390 introduced a bug by just adding a return if DeletePidPageMappingInfoBatch() fails. In the case where no error is returned by DeletePidPageMappingInfoBatch() the function continues with `return impl.DeletePidPageMappingInfoSingle(pid, prefixes)` and fails, as prefixes just got removed.
Fixes https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/392
=> processmanager/ebpf: return on success

.golangci.yml
Because the linter complained:
```
WARN [lintersdb] The linter "exportloopref" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle 
```
=> Remove linter 'exportloopref'

process/process.go
Reduce number of allocations significantly in `parseMappings()`. It also has some positive effects on CPU usage.
```
$ benchstat old.txt new.txt
goos: linux
goarch: amd64
pkg: go.opentelemetry.io/ebpf-profiler/process
cpu: 12th Gen Intel(R) Core(TM) i7-12800H
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
ParseMappings-20   90.92µ ± 5%   85.19µ ± 2%  -6.31% (p=0.000 n=10)
│   old.txt    │               new.txt                │
│     B/op     │     B/op      vs base                │
ParseMappings-20   97.82Ki ± 0%   80.92Ki ± 0%  -17.27% (p=0.000 n=10)
│   old.txt   │              new.txt               │
│  allocs/op  │ allocs/op   vs base                │
ParseMappings-20   438.00 ± 0%   95.00 ± 0%  -78.31% (p=0.000 n=10)
```
The …
=> process: Deduplicate paths in parseMappings()

tracer/tracer.go
On my 16 core local system (VM, possibleCPUs:128, onlineCPUs:16), the previous logic allocated more than 5GB of kernel memory as worst-case (with `off-cpu-threshold` set to 1000) and the agent took ~20 seconds to start due to swapping.
This PR reduces the worst-case down to 5MB.
Fixes #320.
Also see https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/320#issuecomment-2714207299.
=> Fix excessive memory allocation for sched_times (#320)

libpf/convenience_test.go, metrics/ids.go, metrics/metrics.json, process/coredump.go, process/process.go, process/process_test.go, process/types.go, processmanager/manager.go, processmanager/manager_test.go, processmanager/processinfo.go, processmanager/types.go, util/util.go
Fixes #366
I believe this is a remnant from old days.
The agent should not exit if there is a parsing error. Instead, log an error and continue with the next line of the maps file.
**Scope**
- treat parsing errors gracefully
- be more consistent with other parsing code and do not `exit()`
- remove unnecessarily exported functions `util.HexToUint64()` and `util.DecToUint64()`
- the formerly exported functions did not document the exiting behavior
**Not in scope**
- dealing with breaking changes of the maps format (assumption is that this won't happen as it will break many different workflows / tools)
=> Don't exit if parsing of /proc/PID/maps fails

.github/workflows/unit-test-on-pull-request.yml, .gitignore, Dockerfile
This is a complementary change to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/408.
It adds the Rust binary blobs to git and adds a CI check to verify their integrity.
Unfortunately, the Dockerfile needs to be updated to allow this cross compilation for Rust. The CI will fail in the scope of `check-rust-blobs` as the updated docker image will only be available once the changes to the Dockerfile got merged into `main`.
=> Rust: add binary blobs

.github/workflows/unit-test-on-pull-request.yml, Makefile
If binary blobs do not match, this is the output:
```
Run if ! sha256sum --check binary-blobs.hash; then
support/ebpf/tracer.ebpf.release.amd64: OK
support/ebpf/tracer.ebpf.release.arm64: OK
target/x86_64-unknown-linux-musl/release/libsymblib_capi.a: FAILED
sha256sum: WARNING: 2 computed checksums did NOT match
target/aarch64-unknown-linux-musl/release/libsymblib_capi.a: FAILED
Please rebuild and commit the updated binary blobs.
```
I needed to update the Rust blobs with this PR, as paths were not trimmed correctly - see changes around `RUSTFLAGS` in `Makefile`
=> CI: fix blob difference check

metrics/ids.go, metrics/metrics.json, reporter/base_reporter.go, reporter/collector_reporter_test.go, reporter/iface.go, tracehandler/metrics.go, tracehandler/tracehandler.go, tracehandler/tracehandler_test.go
This proposed change implements https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/384#issuecomment-2721165581 as a first step of https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/384/.
=> reporter: simplify TraceReporter interface

collector/internal/controller.go, main.go
`times.New` signature is:
```
func New(reportInterval, monitorInterval,
probabilisticInterval time.Duration) *Times
```
The argument order in `main.go` was swapped, this commit fixes that.
Default for both is 5s, but if you pass args to override the defaults, this would result in incorrect behavior.
=> Fix accidentally swapped reporter and monitor interval

interpreter/apmint/apmint.go, interpreter/dotnet/data.go, interpreter/hotspot/data.go, interpreter/nodev8/v8.go, interpreter/perl/data.go, interpreter/php/opcache.go, interpreter/php/php.go, interpreter/python/python.go, interpreter/ruby/ruby.go, interpreter/types.go, processmanager/execinfomanager/manager.go
This allows interpreter plugins to deallocate memory or uninstall ebpf entries at executable data unload time.
=> Add interpreter.Data.Unload hook

interpreter/loaderinfo.go, process/coredump.go, process/process.go, process/types.go, processmanager/manager_test.go, tools/coredump/new.go, tools/coredump/storecoredump.go
For live processes a direct filename to /proc is returned, and for coredump cases a temporary file is created with the data extracted.
This is a last resort method to access the contets and mainly suitable if the is inspected via 3rd party module/library which does not support Go ReaderAt interface.
prerequisite for #408
=> Add Process.ExtractAsFile interface

rust-crates/symblib/src/gosym/raw/regions.rs, rust-crates/symblib/src/lib.rs, rust-crates/symblib/src/symbconv/go.rs
Noticed Gosym(BadLineNumber) in the go-1.24.0 binary. So I have added handling in symbconv and a test.
```
WARN: bad line number of function (go:textfipsstart)
WARN: bad line number of function (go:textfipsend)
```
=> symblib: Add test case for go binaries symbconv

processmanager/processinfo.go
fix the processName of processInfo always null.
=> Fix /prod -> /proc for processInfo

.github/workflows/unit-test-on-pull-request.yml, CONTRIBUTING.md, README.md, support/README.md
While the Linux kernel LTS support for 4.19 was dropped for some time the oldest supported Linux kernel LTS version is currently 5.4. Update references to use the currently oldest supported Linux kernel LTS version.
Proposed change based on the discussion in https://cloud-native.slack.com/archives/C03J794L0BV/p1744317888826789 - FYI @gnurizen @umanwizard
=> Bump minimal supported kernel version from 4.19 to 5.4

Makefile, rust-crates/symblib-capi/Cargo.toml
1. Removed `cdylib` from Rust build as musl toolchain doesn't support it
2. Simplified `Makefile`
=> Simplify build

interpreter/nodev8/v8.go
DeoptimizationLiteralArray's type disappeared from the metadata, causing many unsymbolizable frames in Node v22. Add it back here.
=> Fix a few more v8 issues

nativeunwind/elfunwindinfo/elfehframe.go, nativeunwind/elfunwindinfo/elfehframe_aarch64.go, nativeunwind/elfunwindinfo/elfehframe_test.go, nativeunwind/elfunwindinfo/elfehframe_x86.go, nativeunwind/elfunwindinfo/elfgopclntab.go, nativeunwind/stackdeltatypes/stackdeltatypes.go, processmanager/execinfomanager/manager.go, processmanager/manager_test.go, processmanager/synthdeltas.go, processmanager/synthdeltas_test.go, support/types.go, support/types_def.go, tools/stackdeltas/stackdeltas.go
Reduce the spread of CGO across the code base and move definitions to support package.
Follow up to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/422#discussion_r2036799445
=> nativeunwind/stackdeltatypes: move cgo definition

reporter/base_reporter.go, reporter/internal/pdata/generate.go, reporter/internal/pdata/generate_test.go, reporter/internal/pdata/pdata.go
In https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/248 the possibile unlimited growth of the inner map `map[libpf.AddressOrLineno]sourceInfo` of the `frames` cache, was identified as potential issue. Replace this regular map with a LRU to limit its size.
=> reporter: replace inner regular map with LRU

support/ebpf/kernel.h
gcc 15 defaults to c23, in which bool, true and false are keywords.
=> Fix build with gcc 15

reporter/base_reporter.go, reporter/internal/pdata/generate.go, reporter/samples/samples.go
As mentioned in the title, this commit primarily aims to add the thread ID attribute to the sent samples. Previously, samples only had the thread name attribute, which couldn't differentiate between samples with same thread names or indicate thread load balancing.
=> Add the thread ID attribute to the sample

.github/renovate.json5
Instead of opening a PR for every dependency (like #476, #477, #478 and others), group dependency update PRs from renovate by their type.
=> CI: group renovate update PRs

.github/renovate.json5
Renovate seems not to support negation for the matchManagers input.
Fixes #493
=> CI: fix renovate negated matchManagers

interpreter/nodev8/v8.go, interpreter/nodev8/v8_test.go
Extend the regexp to match also the nsolid binary name. Add tests for regexp.
fixes #219
=> nodev8: add support for nsolid fork of node

.github/renovate.json5
Follow up to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/499#discussion_r2122844367. As automatic updates of the CI action golangci-lint-action conflicts with other parts, ignore this dependency.
Also set `automerge` for groups that will not break things. This should reduce maintenance burden.
=> CI: Skip automatic updates for golangci/golangci-lint-action

.github/workflows/auto-tag.yml, VERSIONING.md
Add a policy around versioning of this project as well as a Github Action to do this task.
Fixes https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/513
This change brings us in compliance with https://github.com/open-telemetry/opentelemetry-collector-releases/pull/976.
=> Add Versioning

tools/coredump/modulestore/store.go
It seems the OTel S3 endpoint did get more restrictive and now requires a checksum for uploaded items.
Without this checksum, the following error is returned:
failed to upload file: operation error S3: PutObject, https response error StatusCode: 400, RequestID: sjc-1:<some-random-ID>, HostID: , api error InvalidArgument: x-amz-content-sha256 must be UNSIGNED-PAYLOAD or a valid sha256 value.
=> coredump: add checksum for uploads

interpreter/go/go.go
The goData Unload should not releace the pclntab until all goInstances are Detached. Otherwise a Symbolize call can be done with the pclntab released.
Additionally, intern the strings from pclntab lookups using unique to not leak mmapped data referencing string outside this module.
fixes #557
=> interpreter/go: fix referencing mmap area after unload

.github/workflows/auto-tag.yml
Fix the trigger for the auto tagging job. At the moment it would run on every day of January instead of every 1st of each month.
Here is the format:
```
┌───────────── minute (0 - 59)
│ ┌───────────── hour (0 - 23)
│ │ ┌───────────── day of the month (1 - 31)
│ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
│ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
│ │ │ │ │
* * * * *
```
=> ci: fix cron job for auto tagging

reporter/internal/pdata/generate.go
Since we store the ContainerID attribute on the Resource level, we no longer need it at the `sample` level.
=> Drop ContainerID attribute from samples

.github/workflows/codeql.yml
Since the merge of https://github.com/open-telemetry/opentelemetry-ebpf-profiler/commit/e04411c941e658d7229c8022fea4fe842ef149a4 the [CodeQL GH jobs are failing](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/actions/workflows/codeql.yml). It seems like, the job requires more read permissions, than just to the [content](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions).
As this GH job is working in other OTel repositores with `read-all` [set](https://github.com/open-telemetry/opentelemetry-go/blob/0f7f1d0bad21aba18feaadc0171c53705fbda419/.github/workflows/codeql-analysis.yml#L21), also use `read-all`.
=> [ci/codeql] adapt permissions

support/ebpf/tracemgmt.h
condition `errNo != 0` is always false here
=> fix(tracemgmt): remove unnecessary errno check in rate limit reset condition

reporter/internal/pdata/generate.go, reporter/internal/pdata/generate_test.go
mapping_table[0] should now be the only dummy mapping. Previously, the agent generated a unique dummy mapping per frame.
**Also see:**
- #597 
**NOTE**: Devfiler needs to be updated to account for dummy mappings.
=> reporter: Do not generate unique dummy mappings

remotememory/remotememory.go, remotememory/remotememory_linux.go, remotememory/remotememory_other.go, remotememory/remotememory_test.go
This will eventually help allowing running some unit tests (for example coredump tests) without spawning a full linux OS on non linux systems (at least darwin, maybe windows)
=> remotememory: allow compiling on non linux systems

processmanager/ebpf/ebpf.go
Similar to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/612
This PR allows compiling the `processmanager/ebpf` package on `darwin`
This will eventually help allowing running some unit tests (for example coredump tests) without spawning a full linux OS
=> ebpf: use features.BPF_F_NO_PREALLOC constant

Dockerfile
The image may be handy to format/lint C code
```
root@7b6151a22a97:/agent/support/ebpf# make lint
clang-format-17 -Werror --dry-run -style=file *.[ch]
/bin/sh: 1: clang-format-17: not found
make: *** [Makefile:84: lint] Error 127
```
=> Dockerfile: add clang-format-17

Dockerfile
This allows using the installed tools, such as porto in the docker dev container
```
root@3f484fa80ce1:/agent/src# make lint
GOARCH=arm64 go generate ./...
(cd support && ./generate.sh)
go: downloading github.com/jcchavezs/porto v0.7.0
types_gen.go
go: downloading golang.org/x/mod v0.21.0
bash: line 1: porto: command not found
(run: make vanity-import-fix)
make: *** [Makefile:100: vanity-import-check] Error 1
```
=> Dockerfile: add ${GOPATH}/bin to $PATH

.gitignore, support/ebpf/Makefile
I noticed when I change a header, the ebpf program is not recompiled and requires a manual clean.
This change should force recompilation if any dependent header changed
=> ebpf: update Makefile to add header dependencies

.github/workflows/collector-tests.yml
CI [failed](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/actions/runs/16612963509/job/46999600022#step:6:6) with this error:
```
/home/runner/work/_temp/f0dfe594-8d5a-4bf0-bedc-302e04114782.sh: line 1: ./scripts/local-collector: No such file or directory
```
=> CI: fix script path

nativeunwind/elfunwindinfo/stackdeltaprovider.go, nativeunwind/stackdeltaprovider.go, processmanager/execinfomanager/manager.go, processmanager/manager_test.go
No one uses this. It was originally envisioned to be used for possibly implementing alternative provider to fetch the deltas from remove server using the host.FileID. But this is now superceded by the fact that pfelf.Reference is passed and the GnuBuildID or other checksums can be calculated if needed.
=> Remove host.FileID from StackDeltaProvider interface

tracer/tracer.go
When allocating the memory for the kernel frames, set the capacity instead of the size. 
This fixes the following panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc502cd]
goroutine 39 [running]:
unique.Handle[...].Value(...)
/usr/local/go/src/unique/handle.go:27
go.opentelemetry.io/ebpf-profiler/traceutil.HashTrace(0xc0011a14a0?)
/agent/traceutil/traceutil.go:20 +0x8d
go.opentelemetry.io/ebpf-profiler/processmanager.(*ProcessManager).ConvertTrace(0xc0012f8000, 0xc000335110)
/agent/processmanager/manager.go:303 +0x75c
go.opentelemetry.io/ebpf-profiler/tracehandler.(*traceHandler).HandleTrace(0xc0012300f0, 0xc000335110)
/agent/tracehandler/tracehandler.go:147 +0x370 …
```
=> tracer: fix capacity issue

interpreter/golabels/integrationtests/golabels_test.go, interpreter/multi.go, processmanager/execinfomanager/manager.go, processmanager/manager.go
- Add MultiData and MultiInstance types to handle multiple interpreters
- Modify detectAndLoadInterpData to try all loaders instead of stopping at first match
- Use errors.Join for proper compound error handling
- Enables concurrent use of Go tracer and GoLabels on same binary
Fixes issue where only the first matching interpreter loader would be used,
preventing multiple interpreters from handling the same ELF object.
Fixes #687
=> interpreter: Support multiple interpreters for single ELF object

reporter/base_reporter.go, reporter/internal/pdata/generate.go, reporter/samples/samples.go
Report extracted labels.
Follow up to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/687#issuecomment-3189006406
=> reporter: report labels

interpreter/apmint/apmint.go, interpreter/apmint/socket.go, libpf/trace.go, libpf/tracehash.go, libpf/tracehash_test.go, processmanager/manager.go, processmanager/manager_test.go, reporter/base_reporter.go, reporter/samples/attrmgr_test.go, reporter/samples/samples.go, tracehandler/tracehandler.go, tracehandler/tracehandler_test.go, traceutil/traceutil.go, traceutil/traceutil_test.go
This reverts commit b4a95e6e39cb037da0728e58922098462787f920.
The Hash was used as a key to not aggregate traces together. Add acomment about that.
Fixes #732
=> Revert "Remove libpf.Trace.Hash (#673)"

.github/workflows/push-docker-image.yml
Allow users with write permission to manually trigger this workflow.
Currently, the docker build image is only updated, if `Dockerfile` changes. As the Go version was bumped with a recent change, the Go version used in the generate Docker image is not up to date. As a consequence, when the current docker image is used it first has to update its Go version before being able to build everything. Depending on the network connection and processing power, this additional step can introduce noticeable delays.
The suggestion is to allow users with write permission to trigger the generation of new images instead of triggering new images based on changes in `go.mod`, as dependencies are constantly updated and therefore would generate significant noise if with every dependency update also the …
=> CI: add manual trigger for docker image

.github/renovate.json5
Unfortunately #753 shows that this new instruction is not followed by renovate. Therefore, promote `ignorePaths` to a higher level.
=> CI: update renovate

interpreter/ruby/ruby.go
libpf.SliceFrom expects a Slice or a Pointer and panics when given a string:
```
panic: invalid type
goroutine 111 [running]:
go.opentelemetry.io/ebpf-profiler/libpf.SliceFrom({0x2540780?, 0x4bacf40?})
/home/runner/go/pkg/mod/github.com/!data!dog/opentelemetry-ebpf-profiler@v0.0.0-20250808130051-25ec00d52d7a/libpf/convenience.go:43 +0x205
go.opentelemetry.io/ebpf-profiler/interpreter/ruby.(*rubyInstance).getStringCached(0xc00293c380, 0x78721261fbf0, 0xc003a1bb08)
/home/runner/go/pkg/mod/github.com/!data!dog/opentelemetry-ebpf-profiler@v0.0.0-20250808130051-25ec00d52d7a/interpreter/ruby/ruby.go:381 +0x10e
go.opentelemetry.io/ebpf-profiler/interpreter/ruby.(*rubyInstance).Symbolize(0xc00293c380, 0xc002bea480?, 0xc0023c8d80)
/home/runner/go/pkg/mod/github.com/!data!dog/opentelemetry-ebpf-prof …
```
=> ruby: fix panic when logging invalid string

Makefile, interpreter/golabels/integrationtests/golabels_integration_test.go, interpreter/golabels/tls_amd64.go, interpreter/golabels/tls_arm64.go
Go binaries built with -buildmode=pie have slightly different assembly code. On arm64, the runtime.load_g symbol has 2 mov (movz and movk) instructions instead of 1 mov:
0x00000000000c2290 <+0>:	adrp	x27, 0x2ca000 <runtime.itabTableInit+3072>
0x00000000000c2294 <+4>:	ldrsb	x0, [x27, #1766]
0x00000000000c2298 <+8>:	cbz	x0, 0xc22ac <runtime.load_g+28>
0x00000000000c229c <+12>:	mrs	x0, tpidr_el0
0x00000000000c22a0 <+16>:	movz	x27, #0x0, lsl #16
0x00000000000c22a4 <+20>:	movk	x27, #0x10
0x00000000000c22a8 <+24>:	ldr	x28, [x0, x27]
0x00000000000c22ac <+28>:	ret
And on amd64, the runtime.stackcheck symbol has also 2 mov instructions instead of 1:
0x00000000007ec320 <+0>:	mov    $0xfffffffffffffff8,%rcx
0x00000000007ec327 <+7>:	mov    %fs:(%rcx),%rax
This commit fixes the TLS offset retrieval …
=> Improve g TLS offset retrieval for binaries built with buildmode=pie

reporter/internal/pdata/generate.go, reporter/internal/pdata/generate_test.go, reporter/internal/pdata/helper.go
Protocol v1.8.0 introduces a new `Stack` message. This PR adds deduplication for such messages.
Fixes: #808
**TODO:**
- ~Add some tests~
=> Deduplicate Stack messages

collector/factory.go, collector/internal/controller.go, internal/controller/config.go
This allows user-defined configuration of the currently static configurations in the receiver's controller, as mentioned in #817.
cc @Gandem @ogaca-dd
=> Allow user-defined configuration of MaxGRPCRetries and MaxRPCMsgSize

go.mod
Specifying a higher minor version of Go blocks OTel ebpf profiler components to be updated in other OTel components - e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42590/files#r2333188175. Therefore set the patch version to 0.
=> Go: set patch version to 0

reporter/internal/pdata/generate.go, reporter/internal/pdata/generate_test.go
Update used SemConv to v1.36.0 and use new attributes instead of costum key.
=> reporter: update semconv to v1.37.0

tracer/ebpf_integration_test.go
CI tests are expected to fail in https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/824 because of https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/824#discussion_r2372637327.
But as the uprobe program is not loaded, it passes. Fix this by adding the uprobe to `TestAllTracers` config.
=> tracer: load uprobe program in integration tests

collector/controller_options.go, collector/controller_options_test.go, collector/factory.go, collector/internal/controller.go, internal/controller/config.go
This PR adds a callback when the controller is shutting down.
See this [document](https://docs.google.com/document/d/1QGRCABBgA-eJ3BXe0k0oM6MNGdVXvHmgDT675KxCVZo/edit?tab=t.0#heading=h.f2fxlsoa2dqh) for additional requirements.
This PR is part of a series of PRs that replaces https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/811 :
- https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/834
- https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/825
This [PR](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/834) adds a way to configure the ExecutableReporter but our implementation uses life cycle (Start and Stop methods). The callback when the controller is shutting down can be used to call the Stop method of an executable …
=> Add a callback when the controller is shutting down.

collector/controller_options.go, collector/factory.go
This PR exports `Option`.
In the current implementation you cannot write the following code as `options` is not exported.
```go
options := []ebpfcollector.options{} // Doesn't compile
if Enabled {
options = append(options, ebpfcollector.WithExecutableReporter(executableReporter))
options = append(options, ebpfcollector.WithOnShutdown(executableReporter.Stop))
} else {
options = append(options, ebpfcollector.WithOnShutdown(func() error { 
// Some code
return nil 
}))
}
createProfiles = ebpfcollector.BuildProfilesReceiver(options...)
```
Instead you have to use:
```go
var receiverFunc xreceiver.CreateProfilesFunc
if IsEnabled() {
receiverFunc = ebpfcollector.BuildProfilesReceiver(ebpfcollector.WithExecutableReporter(executableReporter),
ebpfcollector.WithOnShutdown(executableReporter.Stop)) …
```
=> Export Option

collector/controller_options.go
At the moment, linters and tests are failing with this error:
```
Error: collector/controller_options.go:43:130: undefined: option (typecheck)
```
=> collector: fix undefined option
