- Makefile
- support/ebpf/Makefile
Resolves https://github.com/elastic/otel-profiling-agent/issues/15
> Makefile: allow docker targets to work on macOS

- go.mod
- go.sum
> Update docker to 27.0.1

- config/tracer_test.go
- libpf/pfelf/file_test.go
- libpf/pfelf/pfelf_test.go
- libpf/pfelf/testdata/fixed-address.ld
Please refer to the individual commits for details.
> Make tests pass on ARM64

- .github/workflows/env/action.yml
- .github/workflows/unit-test-on-pull-request.yml
Based on https://github.com/elastic/otel-profiling-agent/pull/42 and waiting for that to merge to undraft.
> CI: extract common logic into setup action

- cli_flags.go
- main.go
Wrap CLI argument variables into an own type.
This PR is based on #66, which should be merged first.
> Avoid global variables for flag variables

- main.go
- move argument verification into a separate function
- reduce LoC by using helper functions (log+exitCode)
> Cleanup code in mainWithExitCode()

- cli_flags.go
- config/config.go
- config/config_test.go
- hostmetadata/host/host.go
- hostmetadata/host/host_test.go
- main.go
Another small steps moving away from global `config` variables.
> Move tags validation to hostmeta

- reporter/otlp_reporter.go
I had previously added an inner layer of `xsync.RWMutex` to `frames`, but I failed to notice that the LRU's `Get` method returns `V`, not `*V`, so we ended up **copying the mutex on LRU retrieval**, which obviously defeats the purpose of a mutex and didn't fix the data race. This PR adds a pointer level to make the mutex work as intended.
> Fix data race in reporter

- hostmetadata/host/host.go
Provided access to validatedTags.
> hostmetadata/host: Expose validatedTags

- helpers.go
- main.go
Move details from main.go to helper.go
> Add helper function getHostnameAndSourceIP()

- .github/PULL_REQUEST_TEMPLATE
- README.md
The repository is now in OTel hands and under OTel CLA, so people are welcome to contribute now. :)
> Remove warnings about not accepting contributions

- interpreter/hotspot/method.go
- interpreter/hotspot/unsigned5.go
- interpreter/nodev8/v8.go
- interpreter/perl/instance.go
- interpreter/php/instance.go
- interpreter/python/python.go
- interpreter/ruby/ruby.go
- libpf/libpf.go
- processmanager/manager_test.go
- reporter/iface.go
- reporter/otlp_reporter.go
- tools/coredump/coredump.go
- tracer/ebpf_integration_test.go
- util/util.go
Moving the type is part of #132 and was requested [here](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/132#issuecomment-2314866885)
> Move type SourceLineno to libpf

- proc/proc.go
Fix #157
Only crash the process if all modules have null addresses
> Ignore kernel modules with null addresses

- interpreter/php/decode_amd64.c
- interpreter/php/decode_amd64.h
- interpreter/python/decode_amd64.c
- interpreter/python/decode_amd64.h
- libpf/pfelf/testdata/fixed-address.c
- reporter/testdata/test.c
- tools/coredump/testsources/c/brokenstack.c
- tools/coredump/testsources/c/sig.c
- tools/coredump/testsources/c/stackalign.c
- tools/fake-apm-agent/fake-apm-agent-lib.c
- tools/fake-apm-agent/fake-apm-agent.c
- tpbase/fsbase_decode_amd64.c
- tpbase/fsbase_decode_amd64.h
- tpbase/libc_decode_amd64.c
- tpbase/libc_decode_amd64.h
Addressing https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/146#pullrequestreview-2292072057
> Remove references to Elasticsearch from C files

- README.md
Provide updated version of devfiler.
Fixes https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/163
> Readme: provide new version of devfiler

- .github/workflows/unit-test-on-pull-request.yml
- Makefile
- README.md
> Makefile: Fix parallel build for target 'all'

- interpreter/perl/data.go
- interpreter/perl/instance.go
- tools/coredump/testsources/perl/gdb-dump-offsets.py
No compatibility affecting changes observed. Just bump the supported version range.
> perl: support for 5.40.x

- processmanager/processinfo.go
Noticed this while working on #376, minor cleanup.
> processmanager: Don't synchronize a process that's waiting cleanup

- interpreter/dotnet/dotnet.go
- interpreter/hotspot/hotspot.go
- interpreter/nodev8/v8.go
- libpf/fileid.go
Follow up to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/529#discussion_r2145192610
> interpreter: unique FileID stubs

- tools/coredump/cloudstore/cloudstore.go
- tools/coredump/coredump_test.go
- tools/coredump/main.go
Draft that implements the idea laid out in https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/543#discussion_r2171160604.
> coredump: split out cloudstore

- .github/workflows/codeql.yml
Related to https://github.com/open-telemetry/sig-security/issues/148#issuecomment-3051569200.
cc @trask
> Ensure correct CodeQL workflow permissions

- tracer/events.go
This ensures that the tracer after-batch-logic always executes, which was previously not guaranteed in scenarios where userspace could not keep up with events generated by the kernel (typically: off-cpu).
**Also see:**
- #541 
- #330
> tracer: Add limit to number of trace events processed in one batch

- .github/workflows/collector-tests.yml
- support/local-collector.sh
- Forced bash
- Moved to support/
> Update local-collector.sh script

- libpf/pfelf/file.go
- libpf/pfelf/file_test.go
- libpf/pfelf/pfelf.go
- libpf/pfelf/pfelf_test.go
- libpf/trace.go
- processmanager/processinfo.go
Proposal to report Go build ID for Go binaries since some Go binaries don't have a GNU build ID.
> Go: report Go build ID

- interpreter/go/go.go
- interpreter/instancestubs.go
- interpreter/multi.go
- interpreter/types.go
- libpf/pfelf/file.go
- libpf/pfelf/internal/mmap/mmap.go
- libpf/pfelf/internal/mmap/mmap_linux.go
- libpf/pfelf/internal/mmap/mmap_others.go
- nativeunwind/elfunwindinfo/elfehframe.go
- nativeunwind/elfunwindinfo/elfgopclntab.go
- processmanager/manager.go
Alternative approach to https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/798.
> mmap: use MADV_DONTNEED
